/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated by scripts/gen-vams-abi.py; do not edit. */
#ifndef VAMS_KERNEL_ABI_H
#define VAMS_KERNEL_ABI_H

#include <linux/types.h>

#define VAMS_DESC_VERSION_1 1U
#define VAMS_OP_NOP 0x0000U
#define VAMS_OP_MEM_COPY 0x0001U
#define VAMS_OP_MEM_FILL 0x0002U
#define VAMS_OP_CRC32 0x0003U
#define VAMS_OP_VECTOR_ADD 0x0004U
#define VAMS_SUB_F_VERIFY_CRC 0x0001U
#define VAMS_STATUS_SUCCESS 0x0000U
#define VAMS_STATUS_INVALID 0x0001U
#define VAMS_STATUS_FAILED 0x0002U
#define VAMS_STATUS_TIMED_OUT 0x0003U
#define VAMS_STATUS_CANCELLED 0x0004U
#define VAMS_STATUS_RESET 0x0005U
#define VAMS_ERR_NONE 0x0000U
#define VAMS_ERR_UNSUPPORTED_VERSION 0x0001U
#define VAMS_ERR_INVALID_OPCODE 0x0002U
#define VAMS_ERR_INVALID_FLAGS 0x0003U
#define VAMS_ERR_RESERVED_NONZERO 0x0004U
#define VAMS_ERR_DUPLICATE_ID 0x0005U
#define VAMS_ERR_INVALID_LENGTH 0x0006U
#define VAMS_ERR_INVALID_ALIGNMENT 0x0007U
#define VAMS_ERR_ADDRESS_OVERFLOW 0x0008U
#define VAMS_ERR_INVALID_ADDRESS 0x0009U
#define VAMS_ERR_INVALID_TIMEOUT 0x000aU
#define VAMS_ERR_DMA_READ 0x0010U
#define VAMS_ERR_DMA_WRITE 0x0011U
#define VAMS_ERR_ENGINE 0x0012U
#define VAMS_ERR_TIMEOUT 0x0013U
#define VAMS_ERR_CRC_MISMATCH 0x0014U
#define VAMS_ERR_RESET 0x0015U
#define VAMS_ERR_QUEUE_RESET 0x0016U
#define VAMS_ERR_DEVICE_FATAL 0x0017U

struct __packed vams_submission {
	__le16 version;
	u8 opcode;
	u8 flags;
	__le32 command_id;
	__le64 source_dma;
	__le64 destination_dma;
	__le32 length;
	__le32 timeout_ms;
	__le64 user_cookie;
	__le32 expected_crc;
	__le32 reserved0;
	__le64 reserved1;
	__le64 reserved2;
};

struct __packed vams_completion {
	__le32 command_id;
	__le16 status;
	__le16 error_code;
	__le32 bytes_processed;
	__le32 result_crc;
	__le64 user_cookie;
	__le64 device_timestamp;
};

#define VAMS_SUBMISSION_SIZE 64U
#define VAMS_COMPLETION_SIZE 32U

#endif /* VAMS_KERNEL_ABI_H */
