#!/usr/bin/env python3
"""Generate the VAMS v1 wire headers from the authoritative JSON schema."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "abi" / "vams-v1.json"
OUTPUTS = {
    "portable": ROOT / "include" / "vams_abi.h",
    "firmware": ROOT / "firmware" / "include" / "vams_abi.h",
    "kernel": ROOT / "kernel" / "vams_abi.h",
    "qemu": ROOT / "qemu" / "include" / "hw" / "misc" / "vams_abi.h",
}


def constants(schema: dict[str, object]) -> str:
    groups = (
        ("VAMS_OP_", schema["opcodes"]),
        ("VAMS_STATUS_", schema["completion_status"]),
        ("VAMS_ERR_", schema["error_codes"]),
    )
    lines = [f"#define VAMS_DESC_VERSION_1 {schema['descriptor_version']}U"]
    for prefix, values in groups:
        for name, value in values.items():
            lines.append(f"#define {prefix}{name} 0x{value:04x}U")
    return "\n".join(lines)


def fields(items: list[list[str]], types: dict[str, str], indent: str) -> str:
    return "\n".join(f"{indent}{types[kind]} {name};" for name, kind in items)


def render(schema: dict[str, object], dialect: str) -> str:
    if dialect in ("portable", "firmware"):
        spdx = "MIT"
        includes = "#include <stdint.h>"
        types = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t"}
        packed = "__attribute__((packed))"
        guard = "VAMS_ABI_H" if dialect == "portable" else "VAMS_FIRMWARE_ABI_H"
    elif dialect == "kernel":
        spdx = "GPL-2.0-only"
        includes = "#include <linux/types.h>"
        types = {"u8": "u8", "u16": "__le16", "u32": "__le32", "u64": "__le64"}
        packed = "__packed"
        guard = "VAMS_KERNEL_ABI_H"
    else:
        spdx = "GPL-2.0-or-later"
        includes = '#include "qemu/compiler.h"\n#include "qemu/typedefs.h"'
        types = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t"}
        packed = "QEMU_PACKED"
        guard = "HW_MISC_VAMS_ABI_H"

    indent = "\t" if dialect == "kernel" else "    "
    submission = fields(schema["submission"], types, indent)
    completion = fields(schema["completion"], types, indent)
    text = f"""/* SPDX-License-Identifier: {spdx} */
/* Generated by scripts/gen-vams-abi.py; do not edit. */
#ifndef {guard}
#define {guard}

{includes}

{constants(schema)}

struct {packed} vams_submission {{
{submission}
}};

struct {packed} vams_completion {{
{completion}
}};

#define VAMS_SUBMISSION_SIZE {schema['submission_size']}U
#define VAMS_COMPLETION_SIZE {schema['completion_size']}U

#endif /* {guard} */
"""
    return text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))

    changed = []
    for dialect, path in OUTPUTS.items():
        expected = render(schema, dialect)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                changed.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    if changed:
        print("generated ABI files are stale: " + ", ".join(changed), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
